name: Periodic Health Check

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  health_check_ping:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-wabro.fly.dev/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"

      - name: ping success
        if: success()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          description: ping succeeded. 😊
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: ping failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          description: ping failed! !!!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}